### ISSUE TITLE
Priority for plugin issues (meta-issue)

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-irmt-qgis#416]
Here is the list of priorities for the latest issues on the plugin:

- [ ] 1) Improve interaction between OQ engine and Plugin #409 (initial solution in #411)
- [ ] 2) Visualize `avg_losses-mean` output in event-based calculations #414 
- [ ] 3) Include GMPE name when loading layers for gmfs #410 
- [ ] 4) Do not include unnecessary columns when "aggregating by zone" #415
- [ ] 5) Option to visualize csv outputs with the plugin #413
- [ ] 6) Improve layer styling depending on the type of output #326 
Since this can be difficult, for the time being we can have for all layers:
7 classes of color map "spectral - inverted" with "Equal interval"
- [ ] 7) Modify data included in the loaded gmf shapefile #412

**Comment by CatalinaYepes** [comment]
We are also missing the option of visualizing `Ground Motion Fields` from Event-based calculations

**Comment by ptormene** [comment]
> We are also missing the option of visualizing `Ground Motion Fields` from Event-based calculations

Addressed by https://github.com/gem/oq-irmt-qgis/pull/710
