### ISSUE TITLE
Bugs when working with gmfs

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-irmt-qgis#731]
Here is a list of some issues related to the output `Ground Motion Fields` 

- [ ] Broken color ramps (https://github.com/gem/oq-irmt-qgis/issues/728)
- [ ] There is no option to select the realization (GMPE) to be used. Before there was an option.
Currently the user can select an `Event ID`. Information about the ID is available in the `Events` outputs. To know the realization (GMPE), then the user has to check the `Realizations` output.
**Very cumbersome!**
The best option will be to have a dropdown list with the GMPE name, and the `number_of_ground_motion_fields` (https://github.com/gem/oq-irmt-qgis/issues/410).
- [ ] The attribute table is broken (https://github.com/gem/oq-irmt-qgis/issues/730)
- [ ] Continue discussion about attribute table (https://github.com/gem/oq-irmt-qgis/issues/412)

**Comment by CatalinaYepes** [comment]
The plugin in version 3.7 didn't have the second issue reported here.

<img width="483" alt="plugin_3 7" src="https://user-images.githubusercontent.com/6975363/80265206-70743a80-865c-11ea-89d4-1819beea4d0c.png">
